import { test, expect } from '@playwright/test';

test('contact form shows validation errors on empty submit', async ({ page }) => {
  await page.goto('/nl/contact');
  await page.getByRole('button', { name: /Verzenden/ }).click();
  await expect(page.getByText('// Verplicht veld').first()).toBeVisible();
});

test('contact form submits against real /api/contact', async ({ page }, testInfo) => {
  test.skip(
    process.env.E2E_LIVE_API !== '1',
    'requires Resend sandbox credentials (E2E_LIVE_API=1, RESEND_API_KEY, CONTACT_*_EMAIL)',
  );
  test.skip(testInfo.project.name !== 'chromium', 'live-API send runs on chromium only');

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

  await page.goto('/nl/contact');
  await page.fill('input[name="name"]', `E2E ${runId}`);
  await page.fill('input[name="email"]', 'pascal@example.com');
  await page.fill(
    'textarea[name="message"]',
    `End-to-end run ${runId}. Generated by CI against Resend sandbox.`,
  );

  const [response] = await Promise.all([
    page.waitForResponse('**/api/contact'),
    page.getByRole('button', { name: /Verzenden/ }).click(),
  ]);

  expect(response.status(), `POST /api/contact returned ${response.status()}`).toBe(200);
  await expect(page.getByText('// Verzonden')).toBeVisible({ timeout: 15_000 });
});
