import { test, expect } from '@playwright/test';
import { ContactPage } from './pages/contact-page';

test('contact form shows validation errors on empty submit', async ({ page }) => {
  const contact = new ContactPage(page, 'nl');
  await contact.goto();
  await contact.submit();
  await expect(contact.firstValidationError).toBeVisible();
});

test('contact form submits against real /api/contact', async ({ page }, testInfo) => {
  test.skip(
    process.env.E2E_LIVE_API !== '1',
    'requires Resend sandbox credentials (E2E_LIVE_API=1, RESEND_API_KEY, CONTACT_*_EMAIL)',
  );
  test.skip(testInfo.project.name !== 'chromium', 'live-API send runs on chromium only');

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const contact = new ContactPage(page, 'nl');
  await contact.goto();
  await contact.fill({
    name: `E2E ${runId}`,
    email: 'pascal@example.com',
    message: `End-to-end run ${runId}. Generated by CI against Resend sandbox.`,
  });

  const response = await contact.submitAndWaitForApi();
  expect(response.status(), `POST /api/contact returned ${response.status()}`).toBe(200);
  await expect(contact.successBanner).toBeVisible({ timeout: 15_000 });
});
